{"name": "test_add_contact_to_group", "status": "broken", "statusDetails": {"message": "AttributeError: module 'allure' has no attribute 'allure'", "trace": "app = <fixture.application.Application object at 0x000002C3C9BFFC88>, create_contact = [51: 1 1, 53: NT\"Z}Iq^r n r$eTA!Z, 54: fitty  |f, 55: r>F; $}m\"nMV, 56: 1 1, 57: ),?Ay%;_ a(pbbmZT,{lyoOi, ...]\ncreate_group = [32: fatcat  , 33: VZQ^!UU~ ?K&cpym<~G E}P+\", 34: fitcat .+` .>Ms, 35: =WwkyPBpU[y ffOFAWeiAgtJ _ASx]j|D;H, 36: fitcat VVZ  .GIANU, 37: fitcat  , ...], db = <fixture.db.DbFixture object at 0x000002C3C9C0D6D8>\n\n    def test_add_contact_to_group(app, create_contact, create_group, db):\n>       with allure.allure.step('Given a group list'):\nE       AttributeError: module 'allure' has no attribute 'allure'\n\ntests\\test_add_contact_to_group.py:5: AttributeError"}, "start": 1577262173947, "stop": 1577262173948, "uuid": "2544763f-c531-449c-9756-dedae846ac45", "historyId": "f634a9262623e3df4561458404a86003", "testCaseId": "567bbe92d680842f618bb8df9c183990", "fullName": "tests.test_add_contact_to_group#test_add_contact_to_group", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_add_contact_to_group"}, {"name": "host", "value": "otrizno"}, {"name": "thread", "value": "27536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_add_contact_to_group"}]}