{"name": "test_remove_contact_from_group", "status": "broken", "statusDetails": {"message": "AttributeError: module 'allure' has no attribute 'allure'", "trace": "app = <fixture.application.Application object at 0x000002C3C9BFFC88>, create_contact = [51: 1 1, 53: NT\"Z}Iq^r n r$eTA!Z, 54: fitty  |f, 55: r>F; $}m\"nMV, 56: 1 1, 57: ),?Ay%;_ a(pbbmZT,{lyoOi, ...]\ncreate_group = [32: fatcat  , 33: VZQ^!UU~ ?K&cpym<~G E}P+\", 34: fitcat .+` .>Ms, 35: =WwkyPBpU[y ffOFAWeiAgtJ _ASx]j|D;H, 36: fitcat VVZ  .GIANU, 37: fitcat  , ...], db = <fixture.db.DbFixture object at 0x000002C3C9C0D6D8>\n\n    def test_remove_contact_from_group(app, create_contact, create_group, db):\n>       with allure.allure.step('Given a group list'):\nE       AttributeError: module 'allure' has no attribute 'allure'\n\ntests\\test_add_contact_to_group.py:17: AttributeError"}, "start": 1577262174153, "stop": 1577262174153, "uuid": "2a57a72c-aa55-489a-9955-8f2564ef9f66", "historyId": "30bbf72e4b84a171b0cf5bb69c8a9949", "testCaseId": "7151197d1d87c522de0ccfae04b0296b", "fullName": "tests.test_add_contact_to_group#test_remove_contact_from_group", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_add_contact_to_group"}, {"name": "host", "value": "otrizno"}, {"name": "thread", "value": "27536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_add_contact_to_group"}]}